name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # استفاده از جاوا 17
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    # استفاده از آخرین نسخه فلاتر (حذف 3.19.0)
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    # ✅ بخش حیاتی: تایید لایسنس‌ها (بدون این بیلد شکست می‌خورد)
    - name: Accept Android Licenses
      run: |
        yes | flutter doctor --android-licenses

    - name: Clean Project
      run: flutter clean

    - name: Get Dependencies
      run: flutter pub get

    # ساخت APK دیباگ
    - name: Build APK (Debug Mode)
      run: flutter build apk --debug --verbose

    - name: Upload APK
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: build/app/outputs/flutter-apk/app-debug.apk
