name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - uses: subosito/flutter-action@v2
      with:
        # استفاده از نسخه قدیمی‌تر و سازگار (بدون خطای AGP 9)
        flutter-version: '3.19.0'
        # channel: 'stable' را حذف کردم تا مجبور نشود نسخه جدید بگیرد

    # نصب SDK اندروید (حیاتی برای گیت‌هاب)
    - name: Install Android SDK
      uses: android-actions/setup-android@v3

    # تایید لایسنس‌ها (مهم برای جلوگیری از گیر کردن بیلد)
    - name: Accept Android Licenses
      run: yes | flutter doctor --android-licenses

    - name: Flutter Clean
      run: flutter clean

    - name: Get Dependencies
      run: flutter pub get

    # ساخت APK ریلیز
    - name: Build APK
      run: flutter build apk --release --no-tree-shake-icons

    # آپلود فایل نهایی
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
